### ISSUE TITLE
Sub Regions

### ISSUE THREAD

**Issue by vanvanni** [firewolf8385/RegionDisplayName#3]
Hello,

Right now I have a main spawn that contains little sub regions, When I enter a region within the region, the name displayed is still the first region. Not the 2nd one within the 1st one.

Could we get a fix for this? Or can you implement a special Placeholder for that?

**Comment by firewolf8385** [comment]
Are you on the latest version of the plugin? If not, update. This was a bug that should be fixed in the most recent version.

If this is still happening on the latest version, you need to set priorities in your regions https://worldguard.enginehub.org/en/latest/regions/priorities/. The plugin picks the region with the highest priority.

**Comment by vanvanni** [comment]
> Are you on the latest version of the plugin? If not, update. This was a bug that should be fixed in the most recent version.
> 
> If this is still happening on the latest version, you need to set priorities in your regions https://worldguard.enginehub.org/en/latest/regions/priorities/. The plugin picks the region with the highest priority.

Yes I'm! Tried it with the priorities and that indeed worked. Thanks!
